"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useAdminSessionGuard } from "@/hooks/use-admin-session-guard";
import { createParty } from "@/lib/party-api";
import type { PartyType } from "@/types/party.types";

export default function NewPartyPage() { const router = useRouter(); const { session, accessToken, isLoading } = useAdminSessionGuard(); const [type, setType] = useState<PartyType>("INDIVIDUAL"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!accessToken) return; const values = Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string, string>; setSaving(true); try { await createParty(type, values as Record<string, string> & { email: string }, accessToken); router.push("/parties"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create party."); } finally { setSaving(false); } }; if (isLoading || !session) return <main className="page-shell"><p>Checking your session...</p></main>; return <main className="page-shell"><Link className="back-link" href="/parties">Back to parties</Link><div className="page-intro"><p className="eyebrow">New party</p><h1>Create and verify a party</h1><p>Email verification is required before the party becomes active.</p></div><form className="form-card" onSubmit={(event) => void submit(event)}><fieldset className="field-group"><legend>Party type</legend><label><input checked={type === "INDIVIDUAL"} name="type" onChange={() => setType("INDIVIDUAL")} type="radio" /> Individual</label><label><input checked={type === "ORGANIZATION"} name="type" onChange={() => setType("ORGANIZATION")} type="radio" /> Organization</label></fieldset>{type === "INDIVIDUAL" ? <fieldset className="field-group"><legend>Individual details</legend><div className="field-grid"><label>Given name<input name="givenName" required /></label><label>Middle name<input name="middleName" /></label><label>Family name<input name="familyName" required /></label><label>Birth date<input name="birthDate" type="date" /></label><label>Gender<input name="gender" /></label><label>Nationality<input name="nationality" /></label></div></fieldset> : <fieldset className="field-group"><legend>Organization details</legend><div className="field-grid"><label>Legal name<input name="legalName" required /></label><label>Trading name<input name="tradingName" /></label><label>Organization type<input name="organizationType" /></label></div></fieldset>}<fieldset className="field-group"><legend>Contact media</legend><p className="field-help">The required primary email will be verified.</p><div className="field-grid"><label>Email address<input name="email" required type="email" /></label><label>Phone number<input name="phone" type="tel" /></label><label>Physical address<textarea name="address" rows={3} /></label></div></fieldset>{error && <p className="error">{error}</p>}<button disabled={saving} type="submit">{saving ? "Creating..." : "Create party"}</button></form></main>; }
